# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChatChat
    pod 'MBProgressHUD', '~> 1.2'
    pod 'IDMPhotoBrowser', '~> 1.11'
    

end

