# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MessengerApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MessengerApp

  # Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  # Facebook
  pod 'FBSDKLoginKit'

  # Google Sign In
  pod 'GoogleSignIn'

  # Other frameworks
  pod 'MessageKit'
  pod 'JGProgressHUD'
  pod 'RealmSwift'
  pod 'SDWebImage'

end
